<?php

namespace ContactsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function deleteAllStuffConnectWithUser($id)
    {
        $em = $this->getEntityManager();
        $queryForPhones = $em
            ->createQuery('DELETE ContactsBundle:Phone phone WHERE phone.user = :userId')
            ->setParameter('userId', $id);
        $queryForPhones->execute();

        $queryForEmails = $em
            ->createQuery('DELETE ContactsBundle:Email emails WHERE emails.user = :userId')
            ->setParameter('userId', $id);
        $queryForEmails->execute();

        $queryForAddresses = $em
            ->createQuery('DELETE ContactsBundle:Address addresses WHERE addresses.user = :userId')
            ->setParameter('userId', $id);
        $queryForAddresses->execute();
    }

    public function searchForUserByFirstOrLastName($string)
    {
        $em = $this->getEntityManager();
        $query = $em
            ->createQuery('SELECT users FROM ContactsBundle:User users WHERE users.firstname LIKE :firstname OR users.lastname LIKE :lastname')
            ->setParameter('firstname', "%" . $string . "%")
            ->setParameter('lastname', "%" . $string . "%");
        $users = $query->getResult();

        return $users;
    }
}
