<?php

namespace ContactsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function deleteAllStuffConnectWithUser($id)
    {
        $em = $this->getEntityManager();
        $queryForPhones = $em
            ->createQuery('DELETE ContactsBundle:Phone phone WHERE phone.user = :userId')
            ->setParameter('userId', $id);
        $queryForPhones->execute();

        $queryForEmails = $em
            ->createQuery('DELETE ContactsBundle:Email emails WHERE emails.user = :userId')
            ->setParameter('userId', $id);
        $queryForEmails->execute();

        $queryForAddresses = $em
            ->createQuery('DELETE ContactsBundle:Address addresses WHERE addresses.user = :userId')
            ->setParameter('userId', $id);
        $queryForAddresses->execute();
    }
}
